export const REELS_DATA = [
  {
    id: "1",
    title: "Breaking: Major Political Summit",
    category: "Politics",
    image: "https://picsum.photos/400/700?random=1",
    likes: 1200,
    comments: 340,
    shares: 89,
    author: "CNN News",
  },
  {
    id: "2",
    title: "Cricket Finals: Historic Win",
    category: "Sports",
    image: "https://picsum.photos/400/700?random=2",
    likes: 2500,
    comments: 890,
    shares: 456,
    author: "ESPN",
  },
  {
    id: "3",
    title: "Tech Giant Launches New AI",
    category: "Technology",
    image: "https://picsum.photos/400/700?random=3",
    likes: 3400,
    comments: 1200,
    shares: 678,
    author: "TechCrunch",
  },
  {
    id: "4",
    title: "Climate Change: New Report Released",
    category: "Environment",
    image: "https://picsum.photos/400/700?random=4",
    likes: 890,
    comments: 234,
    shares: 123,
    author: "BBC News",
  },
];
