export const dummyNews = [
  {
    id: '1',
    title: 'New Food Street Opens in Adajan',
    content:
      'A brand new food street featuring 20+ food stalls has opened in Adajan area. From locho to pizza, everything available!',
    image: 'https://picsum.photos/400/300?random=1',
    location: 'Adajan, Surat',
    likes: 234,
    comments: 25,
    shares: 10,
    isLiked: false,
    userName: 'Surat City Updates',
    userImage: 'https://i.pravatar.cc/150?img=1',
    timeAgo: '2h ago',
    images: ['https://picsum.photos/600/400?random=1'],
  },
  {
    id: '2',
    title: 'SVNIT Fest Techfest 2024 Announced',
    content:
      'SVNIT announces its annual technical fest. Registrations open from November 1st. Prize pool of 5 lakhs!',
    image: 'https://picsum.photos/400/300?random=2',
    location: 'SVNIT, Surat',
    likes: 456,
    comments: 64,
    shares: 32,
    isLiked: false,
    userName: 'Campus Vibes',
    userImage: 'https://i.pravatar.cc/150?img=2',
    timeAgo: '3h ago',
    images: ['https://picsum.photos/600/400?random=2'],
  },
  {
    id: '3',
    title: 'Traffic Alert: Road Work on Ring Road',
    content:
      'Heavy traffic expected on Ring Road due to ongoing metro construction. Use alternate routes.',
    image: 'https://picsum.photos/400/300?random=3',
    location: 'Ring Road, Surat',
    likes: 89,
    comments: 12,
    shares: 8,
    isLiked: false,
    userName: 'Surat Police',
    userImage: 'https://i.pravatar.cc/150?img=3',
    timeAgo: '5h ago',
    images: ['https://picsum.photos/600/400?random=3'],
  },
  {
    id: '4',
    title: 'Best Locho Challenge Winner Announced',
    content:
      'Lalji Locho wins the "Best Locho in Surat" competition with overwhelming votes. Must try their special tadka!',
    image: 'https://picsum.photos/400/300?random=4',
    location: 'Chowk Bazar, Surat',
    likes: 567,
    comments: 80,
    shares: 27,
    isLiked: false,
    userName: 'Food Lovers Surat',
    userImage: 'https://i.pravatar.cc/150?img=4',
    timeAgo: '1d ago',
    images: ['https://picsum.photos/600/400?random=4'],
  },
];
